name: Android Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Alterado para Java 17
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          arch: x86_64
          profile: Pixel 4
          script: |
            adb devices
            echo "Emulator started!"

      - name: Install dependencies
        run: |
          npm install -g appium
          npm install

      - name: Run tests
        run: |
          npx wdio wdio.conf.js