name: Android Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Accept Android SDK Licenses
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install required Android system image
        run: |
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "system-images;android-31;default;x86_64"

      - name: Create AVD manually
        run: |
          echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd --force -n test_avd --abi 'default/x86_64' --package 'system-images;android-31;default;x86_64' --device 'pixel_3a'

      - name: Reinstall ADB
        run: |
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "platform-tools"

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          arch: x86_64
          profile: pixel_3a  # Ajustado para um dispositivo válido
          avd-name: test_avd  # Usa o AVD criado manualmente
          disable-animations: true
          emulator-options: -no-window -no-audio -no-boot-anim
          script: |
            adb devices
            echo "Waiting for emulator to start..."
            sleep 180  # Aguarda 3 minutos para o emulador inicializar
            adb devices
            echo "Emulator started!"

      - name: Install dependencies
        run: |
          npm install -g appium
          npm install

      - name: Run tests
        run: |
          npx wdio wdio.conf.js
